### ISSUE TITLE
IP + bitmap file from command line?

### ISSUE THREAD

**Issue by vstath** [minlux/dymon#1]
Hello, 

you made my day. Thank you, to start with. 

Perhaps it might be good idea to have the ability to pass arguments to the binary in order to connect to the printer's IP and pass a bitmap file externally also? This way it could be used in shell scripts. 

Perhaps also include some sample bitmap files that work with specific paper sizes? That would make life easier for other people who want to use the wireless printer in Linux. I'm willing to debug and test for you (I am not a coder).

Again, thank you so much!

**Comment by vstath** [comment]
I just saw that this document is mentioning port 9100 

http://download.dymo.com/dymo/user-guides/Print_Server/LWPrintServer_UserGuide_en-US.pdf

I can only assume that it is a similar device (the DYMO Wireless has an ARM CPU based on its web interface log page) and CUPS should be able to drive it? See the Linux section on the above PDF. 

Additionally, there is an old SDK: https://www.dymo-label-printers.co.uk/user/dymo-cups-drivers-1.4.0.tar.gz that mentions how to drive DYMO from Linux with samples. 

Found it on this page: https://www.dymo-label-printers.co.uk/news/download-dymo-sdk-for-linux.html

The CUPS drivers do not show LWW which is very weird because this is not that new of a new model. I didn't manage to print using CUPS no matter what I tried. I was using the 99012 labels. Your software drove the hardware nicely even though sizes and orientation etc didn't match (which is just settings I guess). 

Have you been able to drive this printer in Linux with anything else than your code? Have you gone a different path since you released this code?

**Comment by vstath** [comment]
PPD file found here: https://gist.github.com/vstath/0f5eab715cec427b86dcf9c47f397f04

Not sure if it's of any help but perhaps can see some different options compared to other models (for example the 300x600 dpi etc

**Comment by litepl** [comment]
Hi,

Does this PPD really works ? I'm not able to print any labels... Is LWW compatible with LW450 ? Old LW450 works as expected without probems...

Regards,

Lukasz

**Comment by vstath** [comment]
I took this PPD from my MacOS and it worked fine there. Not sure about Linux though. I didn't manage to make it work IIRC

**Comment by minlux** [comment]
I have updated the project today. The feature to print 1-bit bitmap files from command line was implemented in the application `dymon_bmp`. See the project readme for a short example. 
`doc/label.bmp` is a example bitmap for a 25x25 label.
