### ISSUE TITLE
dymon_pbm.exe and dymon_srv.exe detected as VIRUS

### ISSUE THREAD

**Issue by Roms56** [minlux/dymon#12]
Hello,

After compiling and generating the *.exe files, my Bitdefender antivirus detected them as viruses.
Here are the VirusTotal links: 
https://www.virustotal.com/gui/file/959d2cee9e7060a4c088fad74fac9beca62d40693ca71e03f4829a9b07687131
https://www.virustotal.com/gui/file/4a771ed0f6f50b70ee2352e9a50fe940577d14c8e1b1276730823d54ed5ac5ac

I don't know if this is a false positive, but I'd rather warn you so that you can check for yourself.

Best regards,

**Comment by minlux** [comment]
Don't know what metric your antivirus tool is using to classify executables as virus.

The tool is open source. So you can convince yourself that it isn't a virus!
