### ISSUE TITLE
Change of paper size?

### ISSUE THREAD

**Issue by vstath** [minlux/dymon#2]
Hi there,

thanks for the latest commits. Would it be possible to provide information on how to change the paper (label) size and/or orientation?

The command line options are very useful, thank you for that!

**Comment by joeltrondotcom** [comment]
Did you ever figure this out? I'm in the SAME situation. Minlux's code is the ONLY thing that I could get to work on my device, but the text is too small and its sideways.

**Comment by minlux** [comment]
Today I have updated the project. Now I support two label formats with different orientation:
- 25mm x 25mm, horizontal orientation
- 39mm x 89mm, vertical orientation

Please have a look into  `src/print.cpp`. You can find in the lines 40ff a table that defines those two formats and orientation.

To switch the orientation, the bitmap must be rotated. Therefore I have extended the Bitmap class (see `/src/bitmap/bitmap.cpp`)
